### ISSUE TITLE
Bootstrap 4 File Input deleting a file causing all files to be deleted

### ISSUE THREAD

**Issue by dubillus** [kartik-v/bootstrap-fileinput#1673] opened 2021-01-20 15:04 UTC
## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [ ] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [ ] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [ ] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1.
2.
3.

## Expected behavior and actual behavior

When I follow those steps, I see...

I was expecting...

## Environment

Browsers

- [x] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

Operating System

- [x] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version:
- bootstrap-fileinput version: Si

## Isolating the problem

- [ x] This bug happens [on the plugin demos page](http://plugins.krajee.com/file-input/demo)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using bootstrap-fileinput without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

For example, if I upload 3 files and send to the server it works perfectly and receives all 3, but if I upload 3 files and delete 1 from the preview, there are 2 files remaining in the preview but when sending to the server it passes it as null. It is better said that when eliminating 1 of 3 all the others are eliminated and only the view remains but the arrangement is null.

```
<div class="file-loading">
            <input id="kv-explorer" type="file" name="postedFiles" multiple>
</div>


$(document).ready(function () {

            $("#kv-explorer").fileinput({
                'theme': 'fas',
                'uploadUrl': '#',
                language: 'es',
                overwriteInitial: false,
                initialPreviewAsData: false,
                showUpload: false,
                showCaption: true,
                maxFileCount: 3,
                minFileCount: 1,
                dropZoneEnabled: false,
                'allowedFileExtensions': ['jpg', 'png', 'gif', 'pdf', 'doc', 'docx', 'txt'],
                "fileActionSettings": {
                    "showUpload": false,
                    "showZoom": false
                }
            });

            $("#btnAlerta").click(function () {
                var files = $("#kv-explorer").fileinput("getFileList");
                alert(files);
            });
            

        });

```

**Comment by dubillus** [comment] 2021-04-01 05:39
Hey @dogabudak, I tested FileInput in an asp.net mvc C # application when httpPostedFilebase receives it
as null when individually deleting an image knowing that there are 2 or more images loaded.

**Comment by kartik-v** [comment] 2021-04-28 04:39
Hi could not reproduce this ... hence closing. If there is a demo case somewhere that can be checked - do let know and will reopen.

**Closed by kartik-v** 2021-04-28 04:39 UTC
