### ISSUE TITLE
apk upload error

### ISSUE THREAD

**Issue by weirui** [kartik-v/bootstrap-fileinput#821] opened 2016-12-26 02:44 UTC
## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [ ] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [ ] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [ ] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue
chrome,360 

1. select apk file
2. upload
3.

## Expected behavior and actual behavior

When I follow those steps, I see...

I was expecting...

## Environment

Browsers

- [x] Google Chrome 

Operating System
- [x] Windows

Libraries

- jQuery version:2.2.14
- bootstrap-fileinput version:4.3.6-0

## Isolating the problem

- [ ] This bug happens [on the plugin demos page](http://plugins.krajee.com/file-input/demo)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using bootstrap-fileinput without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by kartik-v** [comment] 2017-06-24 09:31
What is the error you are facing? Unfortunately cannot reproduce your issue?

Am closing this - and will reopen if you can share a demo JS fiddle to understand your issue.

**Closed by kartik-v** 2017-06-24 09:31 UTC
