### ISSUE TITLE
Thumbs of initialPreviewConfig are the same image after upload a new image

### ISSUE THREAD

**Issue by nevits8as** [kartik-v/bootstrap-fileinput#892] opened 2017-03-06 03:27 UTC
## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [ ] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [ ] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [ ] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. Open a modal via load with the fileinput
2. Add a new image
3. The upload its succes and close de modal
4. Open again the modal
5. Delete a image and close de modal
6. Open again the modal and in the initialPreviewConfig the thumbnail its the same as previu image what i delete before.

Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

Operating System

- [x] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version: 2.2.4
- bootstrap-fileinput version: 4.3.9

## Isolating the problem

- [ ] This bug happens [on the plugin demos page](http://plugins.krajee.com/file-input/demo)
- [x] The bug happens consistently across all tested browsers
- [x] This bug happens when using bootstrap-fileinput without other plugins
- [x] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by kartik-v** [comment] 2017-03-06 05:21
>Open again the modal. Delete a image and close de modal. Open again the modal and in the initialPreviewConfig the thumbnail its the same as previu image what i delete before.

You cannot delete the image when modal is open... how are you doing it?

**Comment by kartik-v** [comment] 2017-03-14 03:47
Can you share a JS fiddle to see this issue? Could not reproduce this.

**Comment by nevits8as** [comment] 2017-09-09 20:18
I just change the images versions after the extension of each image.

**Comment by kartik-v** [comment] 2017-09-10 02:59
Cannot reproduce this issue. The latest release of the plugin is v4.4.4 and recommend to come back if the issue persists with a JS Bin / fiddle. Closing this as of now.

**Closed by kartik-v** 2017-09-10 02:59 UTC
