### ISSUE TITLE
No Preview of selected Video after updating to 1.0.8 via composer in Yii2

### ISSUE THREAD

**Issue by pawansgi92** [kartik-v/bootstrap-fileinput#1304] opened 2018-09-24 14:04 UTC
Hi

I updated the plugin according to the mention 

'options' => ['accept' => 'pdf','mp3','mp4','multiple' => true],
        'pluginOptions' => [
            'previewFileType' =>'any',
        ]

But i am unable to view the preview of selected video before uploading it.

**Comment by kartik-v** [comment] 2018-10-05 05:54
Cannot reproduce your issue. Please share a JS fiddle to reproduce. Also since it is related to the yii2-widget-fileinput - please post in the right repo. Closing here.

**Closed by kartik-v** 2018-10-05 05:54 UTC
