### ISSUE TITLE
PDF upload not working, shows spinning wheel, throws js errors

### ISSUE THREAD

**Issue by jrajamaki** [kartik-v/bootstrap-fileinput#1870] opened 2024-08-16 11:52 UTC
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [x] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. Go to [demo](https://plugins.krajee.com/file-basic-usage-demo) page
2. Upload pdf file

## Expected behavior and actual behavior

When I follow those steps, I see spinning wheel without any preview and error in console: `Unhandled Promise Rejection: Error: End-Of-Stream`.

I was expecting, seeing a file-icon as generic preview item.

## Environment

Browsers

- [ ] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer
- [x] Safari

Operating System

- [ ] Windows
- [x] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version:
- bootstrap-fileinput version:

## Isolating the problem

- [x] This bug happens [on the plugin demos page](http://plugins.krajee.com/file-input/demo)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using bootstrap-fileinput without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

## Related
#1822

**Comment by kartik-v** [comment] 2024-08-17 05:18
Greetings. Cannot reproduce this issue in my environment here. Can you check if you have a local environment config conflict or PDF settings on browser preventing you doing something. Try it on different devices and systems to check the issue.

**Comment by jrajamaki** [comment] 2024-08-19 07:56
> Greetings. Cannot reproduce this issue in my environment here. Can you check if you have a local environment config conflict or PDF settings on browser preventing you doing something. Try it on different devices and systems to check the issue.

@kartik-v Hello! Tested with two other machines and also iPhone, does not work with any of them when uploading PDF file using Safari browser. For example, uploading [The Foo Bird](https://digitalcommons.butler.edu/cgi/viewcontent.cgi?article=3552&context=manuscripts) does not work.

**Comment by code-knitter** [comment] 2024-09-05 18:41
Could this be related to #1862 ? The OP doesn't specify whether they use filetype.min.js, but the symptoms match. We had problems that match this description and found that the errors went away when we included filetype.js instead of filetype.min.js as described in #1862

**Comment by kartik-v** [comment] 2024-09-05 19:14
Yes maybe related. The issue #1862 has a resolution. Do check with latest codebase and let know and will reopen this if issue persists.

**Comment by jrajamaki** [comment] 2024-09-18 13:30
@kartik-v - good news is that using `filetype.js` instead of `filetype.min.js` fixes the issue but bad news is that the bug still happens in 1b2aa33 when using `filetype.min.js`.

**Comment by kartik-v** [comment] 2024-09-18 14:07
I have pushed a fix - check if this works. Thanks.

**Comment by jrajamaki** [comment] 2024-09-19 07:46
> I have pushed a fix - check if this works. Thanks.

Yes, this fixed the issue, thank you very much.

Any estimation on new release?

**Comment by kartik-v** [comment] 2024-09-20 15:50
Will post a new release soon.

**Closed** 2024-09-20 15:50 UTC
