### ISSUE TITLE
Unexpected kv-zoom-cache table after upload

### ISSUE THREAD

**Issue by makshh** [kartik-v/bootstrap-fileinput#1212] opened 2018-03-27 10:53 UTC
## Steps to reproduce the issue

1. `Use explorer-fa` theme
2. Upload image when `showZoom` is set to `true` (it's by default)
3. Response from server with initial preview and initial preview config, so new image will appear from the server after upload.

### Config

```js
$('#upload-zdjecia').fileinput({
  uploadUrl: 'myurl',
  theme: 'explorer-fa',
  uploadAsync: true,
  maxFileCount: 50,
  validateInitialCount: true,
  browseOnZoneClick: true,
  overwriteInitial: false,
  showCaption: false,
  browseClass: "btn btn-primary btn-block",
  showUpload: false,
  showRemove: false,
  showClose: false,
  language: 'pl',
  resizeImage: true,
  maxImageWidth: 1920,
  allowedFileExtensions: ['jpg', 'jpeg'],
  initialPreview: initialPrev,
  initialPreviewConfig: initialPrevConf,
  layoutTemplates: {
    preview: previewTemplate,
    footer: footerTemplate,
    actions: actionsTemplate,
    size: '<samp><small>({sizeText})</small></samp>'
  },
  fileActionSettings: {
    removeIcon: 'Usuń <i class="fa fa-trash"></i>',
    removeClass: 'btn btn-sm btn-danger',
    uploadIcon: 'Wgraj <i class="fa fa-upload"></i>',
    uploadClass: 'btn btn-sm btn-info',
    showDrag: false
  }
});
```

### Result

![1](https://user-images.githubusercontent.com/5025950/37963504-bcffd444-31be-11e8-8f21-7f2da67ad9a1.png)

## Expected behavior and actual behavior

When I follow those steps, I see this table with class of `kv-zoom-cache` after image upload and it should be hidden or not there. It works good (I don't see this table) when I'm not returning initial preview and initial preview config from the server or when I set `showZoom` to `false`.

## Environment

Browsers: all

Operating System: Windows, Mac OS X

Libraries

- jQuery version: 3.3.1
- bootstrap-fileinput version: 4.4.8

## Isolating the problem

I can't reproduce it on JSBin, server response required.

**Comment by kartik-v** [comment] 2018-04-04 14:43
It seems you have improper HTML markup (some tags not closed) OR data from the server is corrupting the HTML markup. You need to check your server response. You can cross check the demos where initialPreview is returned from server and is displayed ok.

**Comment by makshh** [comment] 2018-04-04 17:34
Thanks for response @kartik-v 

http://plugins.krajee.com/file-krajee-explorer-fa-demo 
I checked this demo (first one) and after upload image is still in `base64` format so the server not responded with `initialPreview`

**Comment by kartik-v** [comment] 2018-05-02 10:42
It seems some configuration / coding problem at your end and does not seem to be an issue that I can reproduce. You may want to share a JS Fiddle / test to see if your issue can be reproduced. Am closing this and will reopen then.

**Closed by kartik-v** 2018-05-02 10:42 UTC

**Comment by makshh** [comment] 2018-05-04 10:42
Hi,

I made a simple demo

[LINK](http://mcthemes.co.nf/fileinput-example/)

After image upload you can see in the console what I'm returning.
If you try to upload 2 images at once (clicking global `Upload` button) there is no problem. The problem is when you try to upload single image.

**Comment by makshh** [comment] 2018-05-21 12:36
Any news about this issue @kartik-v?

**Comment by kartik-v** [comment] 2018-05-21 13:11
I am not able to see any difference... in mass upload or single upload in the link you shared and both seem to behave OK. What is the issue?

**Comment by kartik-v** [comment] 2018-05-21 13:16
You may need to check the server code that processes the UPLOAD. You seem to be returning some HTML markup or similar in the JSON post your upload. That seems to be breaking the markup.

**Comment by makshh** [comment] 2018-05-22 12:09
Tried. Link is updated and I'm returning only link to the image and I set `initialPreviewAsData` to `true`. It's strange that it works when you click on global `upload` button. I think it's an issue with `fileinput` script. Maybe I'm wrong.

**Comment by sklee2020** [comment] 2020-04-07 10:32
Hi, I'm encountering the same issue.. any solutions for this?

**Comment by blackcofla** [comment] 2022-02-01 15:04
I just went through a big upgrade in a legacy app for jquery and many js plugins we have including this one, I tried setting the "showZoom" option to false but no dice, the preview was still showing two images including the mentioned cache one. I tried a couple of things and didn't work but I don't have time to debug everything and make sure the options are compatible with the new plugin options and stuff like that, long story short, I used `sanitizeZoomCache` option to get rid of the extra image for now:
```javascript
      'sanitizeZoomCache': function (content) {
        return '';
      }
```
And it worked perfectly, hope it helps
