### ISSUE TITLE
Initial preview not rendered again after delete and second upload

### ISSUE THREAD

**Issue by islamw** [kartik-v/bootstrap-fileinput#710] opened 2016-07-10 13:53 UTC
In http://plugins.krajee.com/file-input-ajax-demo/4 example
If I upload files via general upload button and than delete some file, and than upload via general upload button. Initial preview not rendered again.

**Comment by kartik-v** [comment] 2016-07-11 08:30
Cannot reproduce your use case? Can you cross check with demo page and confirm what you are trying to do.

For example, just try your use case in ajax demo 4 above:
- select 2 files and click upload button 
- initial preview is rendered with 2 files
- delete each file from preview
- select 2 more files
- click upload - files are shown in preview as expected

**Comment by kartik-v** [comment] 2016-07-11 08:32
BTW.. I just see for partial deletion of initial preview - there is a JS Error... so will check this separately.

**Comment by kartik-v** [comment] 2016-07-11 09:09
Fixed via 8dd9021.

**Closed by kartik-v** 2016-07-11 09:09 UTC
Labels: bug
