### ISSUE TITLE
File Uploading keeps progressing....

### ISSUE THREAD

**Issue by flybeach** [kartik-v/bootstrap-fileinput#1107] opened 2017-10-24 22:08 UTC
How to replicate:
1. File input is still empty status in drop zone.
2. Click multiple times on x button in drop zone.
3. Try to upload image file now

Result: you will see javascript error in console and input keeps saying "progress"
Expected result: it should be completed successfully

I want you to fix this issue ASAP pls.
Thanks for your good job.

**Comment by kartik-v** [comment] 2017-10-25 03:13
Am unable to reproduce your issue. Is there anything specific to your code?

You can [cross check this ajax demo for example](http://plugins.krajee.com/file-input-ajax-demo/1) and confirm.

**Comment by flybeach** [comment] 2017-10-27 18:34
Its odd thing, I am using this library from CDN link.
Here is my code:
`var imageOption = {
                uploadUrl: '{!! route('sheet.image.store') !!}',
                uploadAsync: true,
                allowedFileExtensions: ["png", "jpg", "jpeg"],
                maxFileCount: 1,
                dropZoneTitle: 'Drag & Drop Image Here ...',
                showUpload: false,
                layoutTemplates: {
                    footer: ''
                },
                previewSettings: {
                    image: {width: "auto", height: "200px", minWidth: "160px"}
                },
                previewFileType: 'image',
                autoReplace: true,
                showUploadedThumbs: false,
                initialPreviewAsData: true,
                @if(!empty($sheet) && !empty($sheet->get('image')))
                initialPreview: ['{!! $sheet->get('image')->getURL() !!}'],
                initialPreviewConfig: [{
                    type: 'image',
                    url: '{!! $sheet->get('image')->getURL() !!}'
                }],
                @endif
                append: false
            };

            image.fileinput(imageOption);
            image.on('filebatchselected', function () {
                $('.fileinput-remove').css('margin-right', '0');
                $('.fileinput-cancel').css('margin-right', '0'); // remove gap between browse and cancel/remove buttons
                image.fileinput("upload");
            });
            image.on('fileuploaded', function (event, data) { // file uploading has been completed!

                $('.fileinput-remove').css('margin-right', '0');
                $('.fileinput-cancel').css('margin-right', '0'); // remove gap between browse and cancel/remove buttons

                // handle response
                let response = data.response; // get Ajax response from server after uploading has been completed
                let fileName = response.file_name; // get file path on the server of file uploaded
                let fileExtension = response.file_extension; // get file extension on the server of file uploaded
                $('[name=imageFileName]').val(fileName);
                $('[name=imageFileExtension]').val(fileExtension);
                $('[name=isImageDeleted]').val(false);
            });
            image.on('filecleared', function (event) {
                $('[name=isImageDeleted]').val(true);
            });`

I am using this library in a lot of sections of my site, all of them are same with this issue.
I wish your help to fix this issue.

Here is error in console I am getting:
![screen shot 2017-10-27 at 11 33 25 am](https://user-images.githubusercontent.com/30245680/32119636-b6e1e582-bb0a-11e7-9e53-6ac2caf99dd7.png)

**Comment by flybeach** [comment] 2017-10-31 01:55
Hello, could you update me pls?
I am waiting for your help..

**Comment by flybeach** [comment] 2017-11-01 14:03
let me know pls if you could replicate the issue or not?
Thanks

**Comment by kartik-v** [comment] 2017-11-12 13:16
Hi... I am unable to reproduce your issue.... check if you can cross check your code... and then share a JS Fiddle or something to check and reproduce.

**Comment by ruby1126** [comment] 2018-03-08 07:27
I have the same problem.

**Comment by kartik-v** [comment] 2018-10-05 08:31
Am unable to reproduce. Closing this. Please open a new issue with a JS Fiddle. Also ensure you have the updated release of the extension.

**Closed by kartik-v** 2018-10-05 08:31 UTC
