### ISSUE TITLE
 File input with preview of images

### ISSUE THREAD

**Issue by pelado66** [kartik-v/bootstrap-fileinput#1364] opened 2019-03-05 12:53 UTC
sorry for my English,
I need to be able to delete / change / add photos to articles on my website, for which I try to implement the demo: [http://plugins.krajee.com/file-input-ajax-demo/3](url)

`<script>
$(document).on("ready",` function() {
    $("#input-702").fileinput({
        theme: 'fa',
        uploadUrl: "/file-upload-batch/1",
        uploadAsync: false,
        minFileCount: 2,
        maxFileCount: 5,
        overwriteInitial: false,
        initialPreview: [
            "http://www.compraensanjuan.com/nv/fotos_tmp2/1353669_1.jpg",
            "http://www.compraensanjuan.com/nv/fotos_tmp2/1353669_2.jpg"
        ],
        initialPreviewAsData: true, // identify if you are sending preview data only and not the raw markup
        initialPreviewFileType: 'image', // image is the default and can be overridden in config below
        initialPreviewConfig: [
            {caption: "casa-1.jpg", size: 576237, width: "120px", url: "/fotos_tmp2", key: "/nv/fotos_tmp2/1353669_1.jpg"},
            {caption: "casa-2.jpg", size: 932882, width: "120px", url: "/site/file-delete", key: 2}, 
        ]
    }).on('filesorted', function(e, params) {
        console.log('file sorted', e, params);
    }).on('fileuploaded', function(e, params) {
        console.log('file uploaded', e, params);
    });
});
</script>`

[http://www.compraensanjuan.com/nv/ej3.php](url)

- The "delete" buttons appear disabled.
- When clicking, they produce error, they do not work.
What's wrong with the code?
Thank you!

@kartik-v

**Comment by kartik-v** [comment] 2019-03-12 06:53
Can you create/share a JS Fiddle to reproduce your issue - as could not reproduce your issue on my environment?

**Comment by kartik-v** [comment] 2019-03-24 17:50
Suggest you to update the plugin to latest release and retry. I am closing this issue as cannot reproduce. In case you still have an issue - please share a JS Fiddle and will reopen this.

**Closed by kartik-v** 2019-03-24 17:50 UTC
