### ISSUE TITLE
locale does not get applied when loaded via requirejs

### ISSUE THREAD

**Issue by ImanMh** [kartik-v/bootstrap-fileinput#459] opened 2015-09-28 08:28 UTC
Please do not close the issue before I verify the problem is resolved! This is a duplicate of #451. You can remove this issue and reopen #451 or continue here. 

Hi, I'm trying to load bootstrap-fileinput and a locale using requireJS. The library is find but the locale does not work when loaded via requireJS. 
Here is my require config: 
```javascript
  shim: {
    'bootstrap': {
      deps: ['jquery']
    },
    'fileinput': {
      deps: ['bootstrap']
    },
    'fileinputFa': {
      deps: ['fileinput']
    }
  }
```
Here is what I've required:

```javascript
require([
  'fileinput',
  'fileinputFa'
], function () {
  $('.up-pic').fileinput({
      language: 'fa',
      allowedFileExtensions: ['jpg', 'png', 'gif'],
  });
});
```
And here is my network panel:

![screen shot 1394-06-31 at 12 35 54](https://cloud.githubusercontent.com/assets/4482199/10014506/88266d16-6126-11e5-9ff3-732f6df6fbb9.png)

Am I doing something wrong?

**Comment by kartik-v** [comment] 2015-09-28 14:39
Cannot reproduce the issue. This is not related to the plugin - but something to check in your application. 

You may check [the plugin docs and multi-language demo](http://plugins.krajee.com/file-multi-lang-demo) to verify the setup for multi language locale support on the same page.

You may try posting this on the Comments and Discussion pages to get help on coding. Use this repo to report plugin specific issues and please avoid raising duplicate issues. Am closing this issue here.

**Closed by kartik-v** 2015-09-28 14:39 UTC

**Comment by ImanMh** [comment] 2015-09-30 08:52
You could add the same comment below my previous issue but you decided to ignore it until I created a new one. I consider issues  such as lack of being AMD friendly an issue of plugin not a problem of end user so that's why I opened an issue instead of asking in stackoverflow. Anyway different opinions.

**Comment by kartik-v** [comment] 2015-09-30 09:05
You may wish to update this thread with any enhancement needed. I am open to suggestions and can open this up. 

Currently as a jquery plugin the functionality is limited to using it out of box - and tests are there for various scenarios. I cannot commit that it will work for every framework or AMD, as its not been tested there. But it should be used and configured by developers accordingly. For your case you can check that locale updates do work if you load the JS in the right order on the page and set the `language` property [as seen in this demo](http://plugins.krajee.com/file-multi-lang-demo) and you need to take this understanding within your app.

Pls do note that I get multiple questions via different forums and github issues (in multiple repos) and unfortunately can only randomly prioritize this during my spare time. While I try to do my best, I do not have a committed specific ETA to respond or close.

**Comment by kartik-v** [comment] 2015-10-23 07:18
This is resolved via #481.

**Comment by jianhong-li** [comment] 2016-11-16 12:15
I also encountered this problem!
when i use this plugin simply without requirejs .everything is ok .
but when i use this with requirejs,it looks like normal,the initialize code seems to work normally. which has no error in the console.but when i upload a file via it.
this plugin does not post the file data to my server using the url which i configed in the initial parameter ,it just post the data to current page url.

the specified js library  as follow:

RequireJS 2.1.15
jQuery JavaScript Library v1.11.2
bootstrap-fileinput v4.3.5

the file loading detail is:

loading css file with  traditional method 
the jquery , bootstrp  and fileinput js loaded by the requirejs.

**Comment by jianhong-li** [comment] 2016-11-16 13:17
i find it works ok with low versions requirejs (1.0.8) 
if your project can use low version requirejs.    you can try this solution
