### ISSUE TITLE
fileuploaded & filebatchuploadsuccess not firing

### ISSUE THREAD

**Issue by jinyuan** [kartik-v/bootstrap-fileinput#993] opened 2017-06-03 07:55 UTC
`$('#fileUpload').fileinput({
            'uploadUrl': '/upload_file_main_process',
            'allowedFileExtensions': ['csv'],
            'uploadAsync': 'true',
            'dropZoneEnabled': false,
            'showPreview': false,
            'required': true,
            'showUpload': false
        });`

` $('#fileUpload').on('filebatchuploadcomplete', function(event, files, extra) {
        console.log('filebatchuploadcomplete');
        $('#fileUpload').fileinput('clear');
    });`

    $('#fileUpload').on('fileuploaded', function(event, data, previewId, index) {

        console.log('File uploaded triggered');
    });

    $('#fileUpload').on('filebatchuploadsuccess', function(event, data, previewId, index) {

        console.log('filebatchuploadsuccess');
    });`

I used a code to trigger the file upload. 
`$('#fileUpload').fileinput('upload');`

```

**Comment by kartik-v** [comment] 2017-06-03 16:24
Cannot reproduce your issue. Can you share a JS Fiddle that reproduces your issue?

**Comment by kartik-v** [comment] 2017-06-24 03:08
Closing this... will reopen if you can share any reproducible issue?

**Closed by kartik-v** 2017-06-24 03:08 UTC
