### ISSUE TITLE
resizing image issue

### ISSUE THREAD

**Issue by ideamartin** [kartik-v/bootstrap-fileinput#1529] opened 2020-03-14 07:59 UTC
cannot select image if image width greater than 200

![image](https://user-images.githubusercontent.com/16500462/76677700-828fa180-65f7-11ea-9123-88f9b6248ad6.png)

![image](https://user-images.githubusercontent.com/16500462/76677710-9d621600-65f7-11ea-9276-12065b492b89.png)

**Comment by ideamartin** [comment] 2020-03-14 08:01
https://plugins.krajee.com/file-image-management-demo#image-resize-width

above demo working in same condition

maxImageWidth: 200,

**Comment by ideamartin** [comment] 2020-04-27 17:49
somebody please?

**Comment by kartik-v** [comment] 2020-05-13 13:09
Please debug and check your local config - seems to be some local issue (maybe duplicate plugin init on same identifier)... try to isolate the problem and if it persists share a JS FIDDLE to reproduce your issue... closing this as of now as cannot reproduce.

**Closed by kartik-v** 2020-05-13 13:09 UTC
