### ISSUE TITLE
showRemove in fileActionSettings doesn't work

### ISSUE THREAD

**Issue by EmmanueleNeri** [kartik-v/bootstrap-fileinput#754] opened 2016-09-05 13:10 UTC
When I put to true showRemove properties in fileActionSettings appears no removal icon in the preview thumbnail.

**Comment by kartik-v** [comment] 2016-09-09 07:20
Get updated code from dev-master.

**Comment by EmmanueleNeri** [comment] 2016-09-09 12:24
Hi,
I updated the code but still does not work.
Please commit the fix #754.

thanks

**Comment by kartik-v** [comment] 2016-09-09 13:35
Not clear with this... or cannot reproduce what you are saying. The remove icon in file thumbnails are seen based on config and can be checked in the [demos](http://plugins.krajee.com/file-input/demo) - by default the remove display is set to true in fileActionSettings ... what is the issue you are facing? Do you have the right configuration?

**Comment by EmmanueleNeri** [comment] 2016-09-09 13:50
the removal of the thumbnail icon appears only if you use drag and drop.
for configurations without drag and drop this icon is not displayed.
This is my configuration i use:

<input id="input-1" name="input6[]" type="file" multiple class="file file-loading">
<script>
    	$(document).on('ready', function() {
		    $("#input-1").fileinput({
		    	language: "it",
		        allowedFileExtensions : ['pdf', 'tif', 'tiff'],
		        maxFileCount: 5,
		        maxFilePreviewSize: 10240,
		        fileActionSettings: {
	            	    showRemove: true 
	                }
		    });
		});
</script>

**Comment by kartik-v** [comment] 2016-09-18 11:56
Please read the [usage modes of the plugin](http://plugins.krajee.com/file-input#usage-modes) to understand what is possible and what is not possible for AJAX mode vs NORMAL form submission mode.

It seems you are using a FORM submission mode (without `uploadUrl`) - in this scenario you cannot REMOVE files already added to preview ONE by ONE... the remove button will ONLY show for content loaded via INITIAL Preview.

Closing this as this is an expected outcome.

**Closed by kartik-v** 2016-09-18 11:56 UTC
