### ISSUE TITLE
Enhance thumbnail preview identifiers

### ISSUE THREAD

**Issue by jianjianxu** [kartik-v/bootstrap-fileinput#1429] opened 2019-06-27 03:07 UTC
this is my code, I used the 5.0.3.

```
$('#upload').fileinput({
		uploadUrl: uploadurl,
		allowedFileExtensions: allowtypes,
		overwriteInitial: false,
		initialPreviewAsData: true,
		maxFileCount: 10,
		dropZoneEnabled: false,
        showRemove:false,
	}).on("filebatchselected", function(event, files) {
		$(this).fileinput("upload");
	}).on('fileuploaded', function(event, data, previewId) {
		console.log(previewId);
		console.log(data.response.path);
	});
```

## Steps to reproduce the issue

1. select 2 files: 01.jpg and 02.jpg
2. click upload button
3. then I get two previewIds like: preview-1561603985653_25-0 and preview-1561603985653_25-1, everything is ok now
4. select 2 more files: 03.jpg and 04.jpg
5. click upload button
6. this time I don't get preview-1561603985653_25-3 and preview-1561603985653_25-4. I get preview-1561603985653_25-0 and preview-1561603985653_25-1 also. And the pic 01 and 02 are overwrote.

Does anybody see the problem like me? Please help me with this. Thank you.

**Comment by kartik-v** [comment] 2019-06-30 05:29
You are already uploading files automatically on file selection via `filebatchselected` event ... why are you clicking upload button again?

**Comment by jianjianxu** [comment] 2019-06-30 06:03
I just wanna to descripe the progress to explain my problem. Even with the filebatchselected event, I can't get the right previewId also. The previewId will be reset to the format like "-0" after the upload finished each time in the same webpage.

I dropped the filebatchselected event, also got the same result：
`$('#upload').fileinput({ language: 'zh', theme: themename, uploadUrl: uploadurl, allowedFileExtensions: allowtypes, overwriteInitial: false, initialPreviewAsData: true, maxFileCount: 10, dropZoneEnabled: false, showRemove:false, }).on('fileuploaded', function(event, data, previewId) { console.log(previewId); console.log(data.response.path); });`

**Comment by kartik-v** [comment] 2019-06-30 07:03
It works fine as intended - every time it generates an unique preview id.

What is the issue?

**Comment by kartik-v** [comment] 2019-06-30 07:15
It works fine as intended and as expected. Every time you select files it generates an unique preview id for each file that you can check via `filebatchselected`. Files that have already been uploaded will not be processed next time.

What is the issue?

**Comment by jianjianxu** [comment] 2019-06-30 11:55
Please test like this：
use this code to get the previewId :
```
.on('fileuploaded', function(event, data, previewId) {
console.log('previewId='+previewId);
})
```
1. select 2 files: 01.jpg and 02.jpg
2. upload
3. then print:
`previewId=preview-1561603985653_25-0`
`previewId=preview-1561603985653_25-1`
4. don't close the page, and select one more files: 03.jpg
5. upload
6. at this time, the console panel print:
`previewId=preview-1561603985653_25-0`
same as first time.
But, if you use F12 to see the source code, it shows `id="preview-1561603985653_25-3"` in the page source code.

I checked the process, I found that the code gave an id `preview-1561603985653_25-0` to the preview DIV first, then count the number of DIVs, then change the last id to the right id : `preview-1561603985653_25-3`.

I think the process of changing the id is a little earlier than getting previewId in the event `fileuploaded`. So that I can't catch the last preview DIV exactly in the event `fileuploaded`. I catch the first DIV like '-0' every time.

In the verson `4.5.3`, there is no problem about this(the code use a rand id each time). But in 5.0.3, it is a problem for me.

Please check again. Thank you very much.

**Comment by kartik-v** [comment] 2019-07-01 14:36
Need to check this and will update.

**Comment by kartik-v** [comment] 2019-07-02 08:44
This is resolved with the above latest commit. Check with the updated code on `dev-master` and confirm. This will be tagged in the next release v5.0.5.

**Closed** 2019-07-02 08:43 UTC
Labels: enhancement
