### ISSUE TITLE
Selecting large files takes a while

### ISSUE THREAD

**Issue by TAiS46** [kartik-v/bootstrap-fileinput#790] opened 2016-10-31 12:51 UTC
If I select a file (as example 100mb) my browser is freezing for about 6 seconds.
If have also disabled the preview. This are my settings:

```
$("#fileinput").fileinput({
	uploadUrl: "http://localhost/upload.php",
	showPreview: false,
	maxFileSize: 512000,
	showUpload: false,
	maxPreviewFileSize: 1,
})
```

I think that the plugin tries to generate an preview because if I enable showPreview it takes also about 6 seconds.

I am confused because it seems that I am the only one with this problem.

Tested on an macbook pro with chrome and safari.

**Comment by because-testing** [comment] 2017-01-16 08:42
I encounter this issue too ,anyone know how to process  it to review just give the preview's background icon instead >

**Comment by kartik-v** [comment] 2017-01-16 17:50
You would need to check your fileinput plugin configuration. Read this [note on the usage section of the page](http://plugins.krajee.com/file-input#usage). Ensure you do not attach a CSS class of `file` to your file input if initializing via javascript.

Currently closing this because your use case cannot be reproduced... in case you have a use case / fiddle to reproduce - pls share and will reopen this.

**Closed by kartik-v** 2017-01-16 17:50 UTC
