### ISSUE TITLE
Setting allowedFileExtensions will show error message but still will add file preview and wont prevent its upload

### ISSUE THREAD

**Issue by JadaVonRuth** [kartik-v/bootstrap-fileinput#1523] opened 2020-02-06 06:15 UTC
I wanted to use the plugin as single video file upload, limited to certain extensions with switchable languages.

## Steps to reproduce the issue - this is my setup

            $("#video-upload-input").fileinput({
                theme: 'fa',
                uploadUrl: uploadEndpointUrl,
                enableResumableUpload: true,
                uploadAsync: false,
                initialPreviewFileType: 'video',
                allowedFileExtensions: allowedExtensions,
                showCancel: true,
                maxFileSize: 10000000,
                resumableUploadOptions: {
                    uploadParamNames: {
                        chunkCount: 'chunkCount',
                        chunkIndex: 'ChunkNumber',
                        chunkSize: 'chunkSize',
                        chunkSizeStart: 'chunkSizeStart',
                        chunksUploaded: 'chunksUploaded',
                        fileBlob: 'File',
                        fileId: 'fileId',
                        fileName: 'fileName',
                        fileRelativePath: 'fileRelativePath',
                        fileSize: 'fileSize',
                        retryCount: 'retryCount'
                    }
                },
                uploadExtraData: function (previewId, index) {

                    var data = { "UploadID": "some guid" };
                    return data;

                }
            }).on('filepreajax', function (event, previewId, index) {

                console.log(event);
                alert('File pre ajax triggered');

            }).on('fileuploaded', function (event, previewId, index, fileId) {

                console.log(event);
                alert('File Uploaded', 'ID: ' + fileId);

            }).on('fileuploaderror', function (event, data, msg) {

                console.log(event);
                alert('File Upload Error', 'ID: ' + data.fileId + ', Thumb ID: ' + data.previewId);
                return false;
            });

## Expected behavior vs. actual behavior

When I follow those steps, i can get error message that I selected file with wrong extension, however file gets added to preview anyways and upload button shows too which I believe it should NOT be like that. Why file gets added to stack? In fileuploaderror there is no event code or event type property which would tell me that it was validation error that happened not something else so I can at least reset the plugin (in case of multi lang site). There is also no filevalidationerror event. And finaly I can still trigger the upload regardless initially failed validation. Is there something I am missing? I expected that file will not be added to upload stack in first case and there wont be any chance of uploading such file.

Browsers

- Google Chrome

**Comment by kartik-v** [comment] 2020-02-06 14:11
Will need to review this...

**Comment by JadaVonRuth** [comment] 2020-04-06 22:07
Any update on this?

**Comment by MostafaRamadan1** [comment] 2020-04-10 20:17
The same for me, I added the  allowedFileExtensions: ["rxml"], an extension that I use, when I drag a folder contain some files that match the extension and some files not matching, it also generate the preview thumbs, it should skip the unwanted extentions

![image](https://user-images.githubusercontent.com/43143956/79020366-ebc3ef80-7b78-11ea-9bf0-c80097a8873b.png)

**Comment by kartik-v** [comment] 2020-04-15 07:13
Can you share a JS Fiddle to reproduce your issue?

Here is an example of [allowedFileExtensions demo](https://plugins.krajee.com/file-advanced-usage-demo#advanced-example-9) where you can see that any other extensions other than the extension mentioned will throw error and not upload them.

**Comment by JadaVonRuth** [comment] 2020-04-15 09:02
I tried on your demo, but it happens there as well, it still adds the preview despite its not wanted. Here is the fiddle https://jsfiddle.net/y8zd20wu/

**Comment by kartik-v** [comment] 2020-04-15 09:24
It shows actually an error thumbnail and not the actual file and is expected outcome for file validation errors as part of the design... This is useful when you drag multiple files of which few files face validation errors based on your plugin config. When you upload... Only files without validation errors will be uploaded.

**Comment by kartik-v** [comment] 2020-04-15 09:32
If you do not want to display error thumbnails as part of your configuration, then set the [removeFromPreviewOnError](https://plugins.krajee.com/file-input/plugin-options#removeFromPreviewOnError) to `true`. Am closing this.

**Comment by JadaVonRuth** [comment] 2020-04-15 09:59
That is one thing yes, that helps but if you try the fiddle, i can select mp3 file and upload it despite allowed extensions are just for video.

**Comment by JadaVonRuth** [comment] 2020-04-15 10:14
![image](https://user-images.githubusercontent.com/9561080/79326151-b02b7b80-7f12-11ea-80b4-607a164d15ee.png)

**Comment by kartik-v** [comment] 2020-04-15 10:26
- The upload button should not trigger any action for such case - it is shown when you have selected files (albiet error files) - will check if something can be done -but as of now even if you click upload in such a scenario - it should not trigger any upload action - because there are no valid files to upload
- The remove button is shown because it should help clearing preview errors and reset the file input once you receive above error.

**Comment by JadaVonRuth** [comment] 2020-04-15 12:50
![image](https://user-images.githubusercontent.com/9561080/79338869-48802b00-7f28-11ea-9a64-4b5b730e1c4f.png)

/someUploadEndpoint is upload url which does not exists (of course) but its being called when upload button is clicked.

**Comment by kartik-v** [comment] 2020-04-20 04:55
Thanks. Will check on this once I get time.

**Comment by kartik-v** [comment] 2020-05-13 07:59
> /someUploadEndpoint is upload url which does not exists (of course) but its being called when upload button is clicked despite it should not initiate any action (ideally not being shown at all till there is at least 1 uploadable file).

I found the reason for the issue you are facing. This is an expected outcome for your use case because you are setting [`uploadExtraData`](https://plugins.krajee.com/file-input/plugin-options#uploadExtraData) - please look at the documentation of this setting. If you remove this property from the plugin config you will get what you need - the plugin will not trigger upload when no files are selected. But if you have set `uploadExtraData` The plugin will allow you to trigger the SUBMIT/UPLOAD action even if there are NO FILES - when you have `uploadExtraData` configured. This is because one typically would use `uploadExtraData` to send other FORM INPUTS of which the FILE INPUT is one of them - so even if no files are uploaded the plugin will trigger the upload action to submit just the inputs set in `uploadExtraData`. 

You have other options to control this behavior - either by returning appropriate message via server code... or use plugin events like `filepreupload` or `filebatchpreupload` or `fileuploaded` or `fileuploaded` or `fileuploadbatchcomplete` or `fileuploadbatchsuccess` or [other fileinput / resumable events](https://plugins.krajee.com/file-input/plugin-events#resumable-events) to track what is set in `uploadExtraData` and do your validation to abort uploads and trigger right message. 

You can also optionally set `uploadExtraData` as a function callback - and let it return a valid data dynamically at runtime or an empty one. 

Am closing this issue based on above.

**Closed by kartik-v** 2020-05-13 07:59 UTC
Labels: to be verified

**Comment by nituthakare** [comment] 2022-07-07 09:29
When i get error in multiple file
my response is like
 {"error":"File not valid, Please try another file","errorkeys":[1,3]}
then i submit again same button no chnages in this files then response is like 
{"error":"File not valid, Please try another file","errorkeys":[0,1]}
@kartik-v can you look into it
