### ISSUE TITLE
Basic config (like `preview` and `remove`) not honored when input is in a BS modal

### ISSUE THREAD

**Issue by fr0z3nfyr** [kartik-v/bootstrap-fileinput#1077] opened 2017-09-12 05:41 UTC
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [x] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. Create a modal on the page with a file input (with or without data attribs with plugin conf `preview` and `upload` as `false`)
2. Init the plugin on said file input
3. Open the modal and upload any file.

## Expected Behavior:
1. The file input should not show a mini preview above the file input upon file selection
2. The file input should not have a `Remove` button displayed upon file selection

## Observed Behavior:
Mini Preview and Remove button are present dis-honoring the plugin conf. Interestingly, when I open the browser developer console and re-open modal multiple times, the input worked as expected sometimes **but not always**. The configuration works as expected when the input is placed on the main page instead of a modal.

## Environment

Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [ ] Internet Explorer
- [x] Safari

Operating System

- [x] Windows
- [x] Mac OS X
- [x] Linux
- [x] Mobile

Libraries

- jQuery version: 2.2.x
- bootstrap version: 3.3.x
- bootstrap-fileinput version: 4.4.x (tested with 4.4.4 as well - latest master)

## Isolating the problem

- [x] I can reproduce this bug in [a jsFiddle](https://jsfiddle.net/pvp8z6kk/)
- [x] The bug happens consistently across all tested browsers
- [x] This bug happens when using bootstrap-fileinput without other plugins
- [ ] This bug happens [on the plugin demos page](http://plugins.krajee.com/file-input/demo)

**Comment by kartik-v** [comment] 2017-09-12 07:02
Nope... cannot reproduce your issue. Seems like some markup and rendering issue on your application.

Check the [basic usage example # 9](http://plugins.krajee.com/file-basic-usage-demo#basic-example-9) for a file input rendered inside a bootstrap modal with `showPreview` and `showUpload` set to `false`.

Closing this. In case you still feel there is an issue, share the details or a js fiddle to reproduce and will open this issue back.

**Closed by kartik-v** 2017-09-12 07:02 UTC

**Comment by kartik-v** [comment] 2017-09-12 07:05
Nope... cannot reproduce your issue. Seems like some markup and rendering issue on your application.

Check the [basic usage example # 9](http://plugins.krajee.com/file-basic-usage-demo#basic-example-9) for a file input rendered inside a bootstrap modal with `showPreview` and `showUpload` set to `false`.

When initializing via javascript - just ensure that you have followed the usage in docs... e.g. do not add the CSS class file to the input as mentioned in the [NOTE in usage on docs](http://plugins.krajee.com/file-input#usage). You need to handle the reinitialization of plugin in case you are dynamically overwriting markups within modal on your page.

Closing this. In case you still feel there is an issue, share the details or a js fiddle to reproduce and will open this issue back.

**Comment by fr0z3nfyr** [comment] 2017-11-14 09:43
> do not add the CSS class file to the input as mentioned in the NOTE in usage on docs

That was it! Was I blind to miss that highlighted text?!! Thanks.
