### ISSUE TITLE
filedeleted

### ISSUE THREAD

**Issue by HKhedr** [kartik-v/bootstrap-fileinput#760] opened 2016-09-16 01:35 UTC
I want to alert response result after delete file but I get undefined
-Script:
 on("filedeleted", function (data, jqXHR) {
        console.log(jqXHR.responseText);
});
-C#
        public JsonResult DeleteFile(string key)
        {
            string fullPath = Request.MapPath(key);
            string result = "File deleted successfully";
            if (System.IO.File.Exists(fullPath))
            {
                System.IO.File.Delete(fullPath);
            }
            return Json(result);
        }

**Comment by AggerChen** [comment] 2017-06-02 06:38
look your fileinput.js file.When the file is deleted，the ajax function property of success have Call the “filedeleted” method like "self._raise('filedeleted', [vKey, jqXHR, extraData]);"
so, maybe you can :
-Script:
on("filedeleted", function(event, key, jqXHR, data) {
     console.log(jqXHR.responseText);
});

**Comment by kartik-v** [comment] 2017-06-24 09:28
Cannot reproduce this issue... so closing. For programming help and support you may use the comments and discussions section of the [plugin docs and demos page](http://plugins.krajee.com/file-input) or head over to the [web tips q&a forum](http://webtips.krajee.com).

**Closed by kartik-v** 2017-06-24 09:28 UTC
