### ISSUE TITLE
Cannot selected one image which has been uploaded and deleted.

### ISSUE THREAD

**Issue by zxy198717** [kartik-v/bootstrap-fileinput#483] opened 2015-10-25 00:26 UTC
1. Test url: http://plugins.krajee.com/file-input-ajax-demo/7
2. Add one image, and click upload icon.
3. Click delete icon.
4. Select the same image again, nothing happened.

Please help to check.

Thanks.

**Comment by kartik-v** [comment] 2015-10-25 19:08
Seems browsers like Chrome do not allow the same file to be selected again in the input until page is refreshed. Can you check and confirm across browsers and OS?

**Comment by zxy198717** [comment] 2015-10-26 01:52
Hi @kartik-v , I checked it on Safari browser, it doesn't work. And the issue only happened after uploading one image successfully, if you haven't clicked `upload icon`, just click `delete icon`, you can select the same image again and again, so I think it isn't the browser's issue, please help to check.

Thanks.

**Comment by kartik-v** [comment] 2015-11-01 09:27
Cannot reproduce this on Chrome or Firefox or IE (not checked on Safari). Meanwhile you may want to update with the following:

- Which browsers you are facing this?
- The steps you are taking to reproduce the problem.

**Comment by zxy198717** [comment] 2015-11-01 11:20
@kartik-v 

Environment:

> * OS: OS X EI Capitan
> * Browser: Chrome 46.0.2490.80

Steps:

> Open Url: [http://plugins.krajee.com/file-input-ajax-demo/7]
> Click `Browse` to select one image
> Click the `upload icon` which is ***below the previewed image***.
> After uploading successfully, click the `remove icon` which is ***below the previewed image***.
> Select the uploaded image again.

**Comment by kartik-v** [comment] 2015-11-02 18:05
This is fixed via latest commit - you can check now.

**Closed** 2015-11-02 18:05 UTC
Labels: bug
